//
// Created by hannes on 17.05.21.
//

#ifndef HHUOS_ICMP4MESSAGETYPE_H
#define HHUOS_ICMP4MESSAGETYPE_H


enum class ICMP4MessageType {
    ECHO_REPLY=0,
    DESTINATION_UNREACHABLE=3,
    SOURCE_QUENCH=4,
    REDIRECT=5,
    ECHO=8,
    TIME_EXCEEDED=11,
    PARAMETER_PROBLEM=12,
    TIMESTAMP=13,
    TIMESTAMP_REPLY=14,
    INFORMATION_REQUEST=15,
    INFORMATION_REPLY=16,
    INVALID_MESSAGE_TYPE
};


#endif //HHUOS_ICMP4MESSAGETYPE_H
