
[ABSOLUTE 0]
gs_offset:      resw 1
pad6:           resw 1
fs_offset:      resw 1
pad5:           resw 1
es_offset:      resw 1
pad4:           resw 1
ds_offset:      resw 1
pad3:           resw 1
edi_offset:	    resd 1
esi_offset:	    resd 1
ebp_offset:	    resd 1
esp_offset:	    resd 1
ebx_offset:	    resd 1
edx_offset:	    resd 1
ecx_offset:	    resd 1
eax_offset:	    resd 1
int_offset:	    resd 1
err_offset:	    resd 1
eip_offset:	    resd 1
cs_offset:	    resw 1
pad2:           resw 1
efl_offset:	    resd 1
uesp_offset:    resd 1
ss_offset:      resw 1
pad1:           resw 1