//
// Created by hannes on 26.06.21.
//

#ifndef HHUOS_DEBUGCONTROL_H
#define HHUOS_DEBUGCONTROL_H

#define DEBUG_SPACING "    "

#define DEBUG_IN_ETH_HEADER
#define DEBUG_IN_ETH_DATABYTES
#define DEBUG_OUT_ETH_HEADER
#define DEBUG_OUT_ETH_DATABYTES

#endif //HHUOS_DEBUGCONTROL_H
