//
// Created by hannes on 16.06.21.
//

#ifndef HHUOS_NETWORKDEFINITIONS_H
#define HHUOS_NETWORKDEFINITIONS_H

#define MAC_SIZE 6
#define IP4ADDRESS_LENGTH 4

#define ARP_RESOLVE_SUCCESS 0
#define ARP_PROTOCOL_ADDRESS_NULL 11
#define ARP_TABLE_NULL 12

#define ECHO_PORT_NUMBER 7 //RFC 862
//TODO: Verify values with RFC Sources
#define UDP4DATAPART_MAX_LENGTH 1500

#define UDP4HEADER_MAX_LENGTH 0xffff
#define BYTEBLOCK_ACTION_SUCCESS 0
#define BYTEBLOCK_NETWORK_DEVICE_NULL 30

#define BYTEBLOCK_BYTES_NULL 31
#define ETHERNETDATAPART_MAX_LENGTH 1500
#define ETHERNETHEADER_MAX_LENGTH 14
#define ETH_DELIVER_SUCCESS 0
#define ETH_FRAME_NULL 21
#define ETH_DEVICE_NULL 22
#define ETH_COPY_BYTEBLOCK_FAILED 23

#define ETH_COPY_BYTEBLOCK_INCOMPLETE 24
#define IP4DATAPART_MAX_LENGTH 576 //Recommended in RFC 791 page 13
#define IP4HEADER_MAX_LENGTH 60 //RFC 791 page 13

#define IP4_DELIVER_SUCCESS 0
#define IP4_DATAGRAM_NULL 1
#define IP4_INTERFACE_NULL 2
#define IP4_RECEIVER_ADDRESS_NULL 3
#define IP4_MATCHING_BITS_FUNCTION_BROKEN 4
#define IP4_NO_ROUTE_FOUND 5

#endif //HHUOS_NETWORKDEFINITIONS_H
